[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
MemoryLayouts = "109d70c3-7bcd-434b-a7d9-3642108a1280"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"
